/**
 * 役名（日本語）から辞書キーへの対応。
 *
 * 役の選択練習と点数計算練習、設定ページの並べ替えがいずれも同じ表示名を
 * 出すため、対応表は 1 つに寄せる。辞書の実体は `score.yaku` 名前空間。
 */
export const YAKU_TO_KEY: Readonly<Record<string, string>> = {
  立直: "riichi",
  一発: "ippatsu",
  門前清自摸和: "menzen_tsumo",
  断么九: "tanyao",
  平和: "pinfu",
  一盃口: "iipeiko",
  役牌: "yakuhai",
  "役牌 東": "bakaze_ton",
  "役牌 南": "jikaze_nan",
  "役牌 西": "jikaze_sha",
  "役牌 北": "jikaze_pei",
  "役牌 白": "haku",
  "役牌 發": "hatsu",
  "役牌 中": "chun",
  三色同順: "sanshoku_doujun",
  一気通貫: "itsu",
  混全帯么九: "chanta",
  七対子: "chitoisu",
  対々和: "toitoi",
  三暗刻: "sanankou",
  三色同刻: "sanshoku_doukou",
  三槓子: "sankantsu",
  小三元: "shosangen",
  混老頭: "honroto",
  ダブル立直: "double_riichi",
  混一色: "honitsu",
  純全帯么九: "junchan",
  二盃口: "ryanpeiko",
  清一色: "chinitsu",
  国士無双: "kokushi",
  四暗刻: "suanko",
  大三元: "daisangen",
  字一色: "tsuiso",
  小四喜: "shousushi",
  大四喜: "daisushi",
  清老頭: "chinroto",
  緑一色: "ryuiso",
  九蓮宝燈: "chuuren",
  四槓子: "sukantsu",
  天和: "tenhou",
  地和: "chihou",
};
